# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 72d91c11fc0dff8c27eeb52bb6535707e8e4bd3c44c75e554bcd8430450c7ad9dfbd00a3535e98c86764ca9cd8f33118b53b32f094b2b33a8d7187a719edc279

test:
  secret_key_base: 45f4ed3ece278445cdccbc547694757f31568fd16ff6e9ae524dbbecd2f62964c4ab27f5699ec047d246344c9c4f1428abe8c192598f5a5e309a62620439516d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
